create table company(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker varchar(10)
);

create table quote(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    company_id int references company(id),
    date date,
    time time,
    open real,
    high real,
    low real,
    close real,
    vol int
);

create table news(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id int references company(id),
    news_text varchar(2000),
    topic varchar(200)
);

create table craudsource(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_id int references news(id),
    positive int,
    negative int,
    neutral int
);

drop table craudsource;
drop table quote;
drop table news;
drop table company;
